import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import 'react-loading-skeleton/dist/skeleton.css'
import 'swiper/css'
import type { Metadata } from 'next'
import React from 'react'
import { ToastContainer } from 'react-toastify'
import AppContextProvider from '../_configs/store/useAppContext'
import { cookies } from 'next/headers'
import { ACCESS_TOKEN_COOKIE_NAME } from '../_configs/constants/cookies'
import { User } from '../_types/user.type'
import { getUserProfile } from '../_api/axios/user'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = cookies()
  let user: User | null = null
  const accessToken = cookieStore.get(ACCESS_TOKEN_COOKIE_NAME)?.value ?? ''
  if (accessToken) {
    const userResponse = await getUserProfile(accessToken)
    user = userResponse
  }
  return (
    <html lang='en'>
      <body>
        <div id='__next'>
          <AppContextProvider
            initUser={user}
            initToken={accessToken}
          >
            <ToastContainer className='w-auto' />
            {children}
          </AppContextProvider>
        </div>
      </body>
    </html>
  )
}
