import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import 'react-loading-skeleton/dist/skeleton.css'
import 'swiper/css'
import type { Metadata } from 'next'
import React from 'react'
import { ToastContainer } from 'react-toastify'
import AppContextProvider from '../_configs/store/useAppContext'
import { cookies } from 'next/headers'
import { ACCESS_TOKEN_COOKIE_NAME } from '../_configs/constants/cookies'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	const cookieStore = cookies()
	const accessToken = cookieStore.get(ACCESS_TOKEN_COOKIE_NAME)?.value ?? ''
	return (
		<html lang='en'>
			<body>
				<div id='__next'>
					<AppContextProvider initToken={accessToken}>
						<ToastContainer className='w-auto' />
						{children}
					</AppContextProvider>
				</div>
			</body>
		</html>
	)
}
